# PACKAGES antora@3.2.0-alpha.2 @antora/atlas-extension:1.0.0-alpha.1 @antora/collector-extension@1.0.0-alpha.3 @springio/antora-extensions@1.3.0 @asciidoctor/tabs@1.0.0-beta.3 @springio/asciidoctor-extensions @opendevise/antora-release-line-extension@1.0.0
#
# The purpose of this Antora playbook is to build the docs in the current branch.
antora:
  extensions:
  - '@antora/collector-extension'
  - id: '@antora/atlas-extension'
    require: '@antora/atlas-extension'
    enabled: false
  - '@springio/antora-extensions/latest-version-extension'
  - require: '@springio/antora-extensions/root-component-extension'
    root_component_name: 'cli'
  - require: '@springio/antora-extensions/asciinema-extension'
site:
  title: Spring CLI Reference
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: docs
    worktrees: true
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/questions/tagged/spring
    hide-uri-scheme: '@'
    page-pagination: ''
    primary-site-url: https://docs.spring.io/spring-cli/reference
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
  - '@springio/asciidoctor-extensions/include-code-extension'
  sourcemap: true
urls:
  latest_version_segment: ''
# runtime:
#   log:
#     failure_level: warn
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.7/ui-bundle.zip
    snapshot: true
